### ISSUE TITLE
CRAN revisions

### ISSUE THREAD

**Issue by stephenturner** [signaturescience/pracpac#95]
- [x] dois in DESCRIPTION
- [x] single quote pkg/software names
- [x] remove examples for unexported functions (apparently even the example pkg is still parsed)
- [x] write to tempdir or similar in examples and vignettes
- [ ] ~default path argument: ???~

From CRAN initial submission: 

```
Please always write package names, software names and API (application 
programming interface) names in single quotes in title and description.
e.g: --> 'Docker', 'R', 'pracpac', 'renv'
Please note that package names are case sensitive.

If there are references describing the methods in your package, please 
add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: <https:...>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for 
auto-linking. (If you want to add a title as well please put it in 
quotes: "Title")

You have examples for unexported functions. Please either omit these 
examples or export these functions.
Examples for unexported function
   isay() in:
      isay.Rd
   handle_use_case() in:
      handle_use_case.Rd
   pkg_root() in:
      pkg_root.Rd

Please ensure that your functions do not write by default or in your 
examples/vignettes/tests in the user's home filespace (including the 
package directory and getwd()). This is not allowed by CRAN policies. 
Please omit any default path in writing functions. In your 
examples/vignettes/tests you can write to tempdir(). -> R/docker.R
```

Looks like @vpnagraj is already on this at the cran-edits branch https://github.com/signaturescience/pracpac/tree/cran-edits. Feel free to assign me if/when needed.

**Comment by vpnagraj** [comment]
yeah im on this. working through the tempdir in examples/vignettes now

**Comment by vpnagraj** [comment]
@stephenturner before i spend too much time plugging this in ... confirm if you think this approach makes sense:

```
ex_pkg_src <- system.file("hellow", package = "pracpac", mustWork = TRUE)
file.copy(from = ex_pkg_src, to = tempdir(), recursive = TRUE)

build_pkg(pkg = file.path(tempdir(), "hellow"))
```

that prefix of copying the pkg src to tempdir() would have to persist through **all** examples. 

lmk what you think.

**Comment by stephenturner** [comment]
This is fine. Maybe we can mention in the `@description` or `@details` how it actually works as default. I might suggest adding this additional documentation in 1.0.1 with NEWS.md being updated documentation or similar.

**Comment by vpnagraj** [comment]
going to resubmit to CRAN shortly ... closing

see comments https://github.com/signaturescience/pracpac/blob/main/cran-comments.md
